export const projectData = [
    {
        id:1,
        titleModal : 'Property Analysis',
        externalLinkTitle : "PropAnalysis WebPage",
        externalLink : "https://www.mlkcompanies.com/RETracker/index.php",
        bodyModalDescription : "This is a full system already installed on a server of a client. This system is built on PHP for the BackEnd and for the FrontEnd was used Bootstrap, Jquery, CSS3. Also is used Datatables,Google Maps , Zillow API, Google API, Melissa API, PHPEXCEL. The system helps to the agents to analyse a property with all the information needed to create an offer or to ignore the property. Right now have 3 markets DFW, HOU and ATL",
        imgURL: "assets/img/PropAnalysis.gif",
        imgAlt : "Property Analysis",
        is_External: true
    },
    {
        id:2,
        titleModal : 'BackEnd Ajax Project',
        externalLinkTitle : "BackEnd Ajax Project",
        externalLink : "http://rcconsultingmx.com/gitProjects/backend_ajax/",
        bodyModalDescription : "This app can help you to show the list of properties depending on the city that is selected. Is developed on Jquery and PHP",
        imgURL: "assets/img/backendAjax.gif",
        imgAlt : "BackEnd Ajax Project",
        is_External: true
    },
    {
        id:3,
        titleModal : 'Calculator',
        bodyModalDescription :'This Calculator can be very useful for people that dont have a local app ',
        imgURL: "assets/img/calculator.png",
        imgAlt : "Calculator",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/Calculadora",
        githubPageLink :"https://izaack89.github.io/Calculadora/ProyectoFinalGermanRamirez-Javascript/",
        githubRepoText :"Calculator Repo",
        githubPageText :"Calculator Live",
    },
    {
        id:4,
        titleModal : 'Sport Almanac',
        bodyModalDescription :'This application will help you to get the information of the games depending of the League. Also if are videos available can show the videos of past games',
        imgURL: "assets/img/sportAlmanac.gif",
        imgAlt : "Sport Almanac",
        is_External: false,
        githubRepoLink :"https://github.com/adina-hc/sports-almanac",
        githubPageLink :"https://adina-hc.github.io/sports-almanac/",
        githubRepoText :"Sport Almanac Repo",
        githubPageText :"Sport Almanac Live",
    },
    {
        id:5,
        titleModal : 'Code Base',
        bodyModalDescription :'This Quiz is to help you to understand Javascript so take the quiz and you can find on what topics you should review or you can demostrate that you are a Master.',
        imgURL: "assets/img/codeBase.gif",
        imgAlt : "Code Base",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/code-base",
        githubPageLink :"https://izaack89.github.io/code-base/",
        githubRepoText :"Code Base Repo",
        githubPageText :"Code Base Live",
    },
    {
        id:6,
        titleModal : 'Day Planner',
        bodyModalDescription :'This Day Planner will help you to organize your daily activities and check with a friendly front-end that will let you know if the hour is on the past, the current hour and on the future',
        imgURL: "assets/img/dayPlanner.gif",
        imgAlt : "Day Planner",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/day-planner",
        githubPageLink :"https://izaack89.github.io/day-planner/",
        githubRepoText :"Day Planner Repo",
        githubPageText :"Day Planner Live",
    },
    {
        id:7,
        titleModal : 'School System',
        bodyModalDescription :'This application was developed for students and teachers that need an app for their school and need to control their assignments, time and take overall control of their tasks.',
        imgURL: "assets/img/schoolSystem.gif",
        imgAlt : "School System",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/school-system",
        githubPageLink :"https://infinite-chamber-84516.herokuapp.com/",
        githubRepoText :"School System Repo",
        githubPageText :"School System Live",
    },
    {
        id:8,
        titleModal : 'Weather Dashboard',
        bodyModalDescription :'With this app you can know the weather of a City with 5 day forecast. This will help you to planify your activities according to the weather prediction.',
        imgURL: "assets/img/dashboardWeather.gif",
        imgAlt : "Weather Dashboard",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/weather-dashboard",
        githubPageLink :"https://izaack89.github.io/weather-dashboard/",
        githubRepoText :"Weather Dashboard Repo",
        githubPageText :"Weather Dashboard Live",
    },
    {
        id:9,
        titleModal : 'Tech Blog',
        bodyModalDescription :'This project will help to create a blog for tech. So you can invite your friends to signup and to share their knowledge about subject of tech ',
        imgURL: "assets/img/systemView.gif",
        imgAlt : "Tech Blog",
        is_External: false,
        githubRepoLink :"https://github.com/izaack89/tech-blog",
        githubPageLink :"https://floating-garden-59968.herokuapp.com/login",
        githubRepoText :"Tech Blog Repo",
        githubPageText :"Tech Blog Live",
    }
    
  ];